language: java

env: DISPLAY=:99

jdk: oraclejdk8

install:
  - sudo apt-get update
  - sudo apt-get install metacity

before_script:
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS="-Xmx1g"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
  - metacity --sm-disable --replace &

script: 
  - mvn clean integration-test -f ch.acanda.eclipse.pmd/pom.xml -B
  - mvn clean integration-test -f ch.acanda.eclipse.pmd/pom.xml -B -Declipse-release=juno
  - mvn clean integration-test -f ch.acanda.eclipse.pmd/pom.xml -B -Declipse-release=kepler
  - mvn clean integration-test -f ch.acanda.eclipse.pmd/pom.xml -B -Declipse-release=luna
  - mvn clean integration-test -f ch.acanda.eclipse.pmd/pom.xml -B -Declipse-release=mars
