language: java

env: 
  global:
    - DISPLAY=:99
    - MAVEN_OPTS="-Xmx512m"
  matrix:
    - ECLIPSE_RELEASE=""
    - ECLIPSE_RELEASE="-Declipse-release=juno"
    - ECLIPSE_RELEASE="-Declipse-release=kepler"
    - ECLIPSE_RELEASE="-Declipse-release=luna"
    - ECLIPSE_RELEASE="-Declipse-release=mars"
    
jdk: oraclejdk8

install:
  - sudo apt-get update
  - sudo apt-get install metacity

before_script:
  - sudo rm /etc/mavenrc
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
  - metacity --sm-disable --replace &

script: mvn clean integration-test -f ch.acanda.eclipse.pmd/pom.xml -B $ECLIPSE_RELEASE
