dist: xenial
language: java
jdk: openjdk8

env:
  global:
    - MAVEN_OPTS="-Xmx512m"
  matrix:
    - ECLIPSE_RELEASE="-PskipSWTBot"
    - ECLIPSE_RELEASE="-Declipse-release=juno -PskipSWTBot"
    - ECLIPSE_RELEASE="-Declipse-release=kepler -PskipSWTBot"
    - ECLIPSE_RELEASE="-Declipse-release=luna"
    - ECLIPSE_RELEASE="-Declipse-release=mars"
    - ECLIPSE_RELEASE="-Declipse-release=neon"
    - ECLIPSE_RELEASE="-Declipse-release=oxygen"
    - ECLIPSE_RELEASE="-Declipse-release=photon"
    - ECLIPSE_RELEASE="-Declipse-release=2018-09"
    - ECLIPSE_RELEASE="-Declipse-release=2018-12"
    - ECLIPSE_RELEASE="-Declipse-release=2019-03"
    - ECLIPSE_RELEASE="-Declipse-release=2019-06"

services:
  - xvfb

cache:
  directories:
    - $HOME/.m2

install: true

script: mvn clean verify -f ch.acanda.eclipse.pmd/pom.xml -B $ECLIPSE_RELEASE
